### ISSUE TITLE
./build.sh failed

### ISSUE THREAD

**Issue by MatanTubul** [nowsecure/dirtycow#4]
i got the following error:

```
`compilation terminated.
cp: cannot stat 'io_dirtycow.so': No such file or directory
In file included from exploit.c:41:0,
                 from cowpy.c:6:
ptrace.c: In function ‘debuggee’:
ptrace.c:24:3: warning: implicit declaration of function ‘err’ [-Wimplicit-function-declaration]
   err (1, "ptrace(PTRACE_TRACEME)");
   ^
ptrace.c: In function ‘ptrace_memcpy’:
ptrace.c:39:4: warning: implicit declaration of function ‘warn’ [-Wimplicit-function-declaration]
    warn("ptrace(PTRACE_POKETEXT)");
    ^
ptrace.c: In function ‘ptraceThread’:
ptrace.c:82:8: warning: implicit declaration of function ‘clone’ [-Wimplicit-function-declaration]
  pid = clone (debuggee, child_stack + sizeof (child_stack) - 8, flags, arg);
        ^
/tmp/cc7Rurmf.o: In function `dirtycow':
cowpy.c:(.text+0x614): undefined reference to `pthread_create'
cowpy.c:(.text+0x631): undefined reference to `pthread_create'
cowpy.c:(.text+0x657): undefined reference to `pthread_create'
cowpy.c:(.text+0x674): undefined reference to `pthread_create'
cowpy.c:(.text+0x685): undefined reference to `pthread_join'
cowpy.c:(.text+0x69d): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
`
```

**Comment by trufae** [comment]
Use the makefile

**Comment by MatanTubul** [comment]
@trufae 
when i execute "make" i get the following error:

```
Package r_util was not found in the pkg-config search path.
Perhaps you should add the directory containing `r_util.pc'
to the PKG_CONFIG_PATH environment variable
No package 'r_util' found
Package r_io was not found in the pkg-config search path.
Perhaps you should add the directory containing `r_io.pc'
to the PKG_CONFIG_PATH environment variable
No package 'r_io' found
cc -shared -fPIC -o io_dirtycow.so io_dirtycow.c 
io_dirtycow.c:3:24: fatal error: r_userconf.h: No such file or directory
compilation terminated.
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by trufae** [comment]
You have to install radare2 to build the plugin

**Comment by MatanTubul** [comment]
do you know if this vulnerability should work on android 7.0

**Comment by trufae** [comment]
Yep it is, unless you install the last security update from google. I wrote a blogpost in the nowsecure blogpost about this

**Comment by MatanTubul** [comment]
i do not know currently i have android 7.1.1 and other device with 7.0

**Comment by trufae** [comment]
Thats up to the kernel version. Only nexus devices got the fix

**Comment by MatanTubul** [comment]
OK i succeeded ti run it but i am not sure how should i execute it?
currently i run "./dcow" but  it is look like is missing 2 parameters "[src] [dst]" what are those parameters?

**Comment by trufae** [comment]
are you running this script inside Termux? this repo is suposed to be compiled in the target device itself. I have extended the README with a crosscompilation section

**Comment by MatanTubul** [comment]
Ok
 in order to run it on android device i should clone the radere2 repo and install it.
in addition you say i should clone the Termux repo? 
i dont understand what should be done first in order to compile it?

**Comment by trufae** [comment]
You dont need to clone radare or termux repo. Just install termux in android and clone this dirtycow repo in there.

R2 is already packaged in termux, if you want to build this on a computer you'll need to clone the repo of r2 because it contains the script to crosscompile and the sources to link the dirtycow plugin. But depending on what you need. Just cowpy is enough.

Cowpy copies the contents of the file src into the dst file. There's not much more to explain here, the source code is pretty small, did you read it? Or the readme?

**Comment by MatanTubul** [comment]
OK i understand you.
i downloaded termux into android device and clone the project. 
when i run build.sh i got the follwoing error:
gcc not found

should i install it also?

**Comment by MatanTubul** [comment]
now u run the build.sh within the termux and i get the following error:
![screenshot_20170103-112309](https://cloud.githubusercontent.com/assets/7632384/21603639/70188590-d1a7-11e6-8cc5-9eefa8a7328b.png)

**Comment by trufae** [comment]
Use make to build. If you want the r2 plugin you must install the radare2-dev package or just build r2 inside termux toget that missing include file, and yes, you need to install make, clang, git...

Cowpy doesnt needs r2

**Comment by MatanTubul** [comment]
when i use "make" i stell get the same error

**Comment by MatanTubul** [comment]
i execute cowpy with the following parameters:
./cowpy hosts /system/etc/hosts

the output id "Done" but the hosts file under etc has no changes

**Comment by trufae** [comment]
dirtycow exploits a race condition, the number of iterations depend on the cpu and the system load. change that in the code or run the program multiple times

**Comment by MatanTubul** [comment]
what do you mean "the number of iterations depend on the cpu and the system load"

**Comment by trufae** [comment]
do you know what’s a race condition?

**Comment by MatanTubul** [comment]
yes i understand what is it, but i m not sure if i should customize the code in order to get it work on my device.

**Comment by radare** [comment]
Please see the last two commits

**Comment by KindlyOnes** [comment]
> now u run the build.sh within the termux and i get the following error:
> ![screenshot_20170103-112309](https://cloud.githubusercontent.com/assets/7632384/21603639/70188590-d1a7-11e6-8cc5-9eefa8a7328b.png)



Hi
Can you give me a guide on how to do this on android?  I really would be very pleased.

**Comment by trufae** [comment]
You need radare2-dev or compile it from source
